spring:
  application:
    name: coupon-eureka
server:
  port: 10001
eureka:
  instance:
    hostname: peer2
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:10000/eureka
